CRITICAL - 2024-03-01 03:18:22 --> ErrorException: Cannot use empty array elements in arrays
in APPPATH\Controllers\TransaksiController.php on line 131.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-03-01 07:17:23 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CI-4.4.5\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\CI-4.4.5\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'bank_sampah', 3306, '', 0)
#1 C:\xampp\htdocs\CI-4.4.5\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CI-4.4.5\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CI-4.4.5\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\CI-4.4.5\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\CI-4.4.5\app\Controllers\UserController.php(177): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\CI-4.4.5\system\CodeIgniter.php(941): App\Controllers\UserController->login()
#7 C:\xampp\htdocs\CI-4.4.5\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#8 C:\xampp\htdocs\CI-4.4.5\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI-4.4.5\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CI-4.4.5\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\CI-4.4.5\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CI-4.4.5\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CI-4.4.5\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\CI-4.4.5\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#4 C:\xampp\htdocs\CI-4.4.5\app\Controllers\UserController.php(177): CodeIgniter\Model->countAllResults()
#5 C:\xampp\htdocs\CI-4.4.5\system\CodeIgniter.php(941): App\Controllers\UserController->login()
#6 C:\xampp\htdocs\CI-4.4.5\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#7 C:\xampp\htdocs\CI-4.4.5\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CI-4.4.5\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-01 07:17:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`
WHERE `userid` = :userid:
AND `password` = :password:
AND `status` = :status:', [...], false)
 3 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 4 APPPATH\Controllers\UserController.php(177): CodeIgniter\Model->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->login()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
